export const CREATE_STREAM = 'CREATE_STREAM';
export const FETCH_ALL_STREAMS = 'FETCH_STREAMS';
export const FETCH_STREAM = 'FETCH_A_STREAM';
export const EDIT_STREAM = 'EDIT_STREAM';
export const DELETE_STREAM = 'DELETE_STREAM';
